# Generated by Django 5.1.1 on 2024-10-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainContet',
            new_name='MainContent',
        ),
    ]
